authenticator/urls.py
from django.conf.urls import url
from . import views

app_name = 'authenticator'

urlpatterns = [
    url(r'^$', views.authenticator_page, name='authenticator_page'),
    url(r'^api/google$', views.google, name='google'),
    url(r'^captcha$', views.captcha_page, name='captcha_page'),
    url(r'^api/get_new_captcha$', views.get_new_captcha),
    url(r'^api/submit_form$', views.submit_form),
]

blogproject/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from . import views
from user import views as user_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^authenticator/', include('authenticator.urls')),
    url(r'^$', views.index_page),
    url(r'^imgcode', include('captcha.urls')),
    url(r'^user/', include('user.urls')),
    url(r'^login$', user_views.login_page, name="login_page"),
    url(r'^register$', user_views.register_page, name="register_page"),
]

user/urls.py
from django.conf.urls import url
from . import views

app_name = 'user'

urlpatterns = [
    url(r'^$', views.user_page, name="user_page"),
    url(r'^api/sign_in$', views.sign_in, name="sign_in"),
    url(r'^api/sign_up$', views.sign_up, name="sign_up"),
    url(r'^api/sign_out$', views.sign_out, name="sign_out"),
    url(r'^setting$', views.setting_page, name="setting_page"),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
        <title>YK</title>
    {% endblock %}
    <link rel="stylesheet" type="text/css" href="{% static 'layui/css/layui.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'authenticator/css/common.css' %}"/>
    <script src="https://apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js"></script>
    <script src="{% static 'layui/layui.js' %}"></script>
    {% block link %}
    {% endblock %}
</head>
<body>
{% block header %}
    <div>
        <ul class="layui-nav layui-bg-molv" lay-filter="">
            <li class="layui-nav-item" id="nav_home"><a href="/">主页</a></li>
            <li class="layui-nav-item" id="nav_captcha"><a href="{% url 'authenticator:captcha_page' %}">图片验证码</a></li>
            <li class="layui-nav-item" id="nav_authenticator"><a href="{% url 'authenticator:authenticator_page' %}">谷歌验证码</a></li>
            <li class="layui-nav-item" id="nav_user">
                <a href="{% url 'user:user_page' %}">我的</a>
                {% if is_login %}
                    <dl class="layui-nav-child"> <!-- 二级菜单 -->
                    <dd><a href="{% url 'user:user_page' %}">个人中心</a></dd>
                    <dd><a href="{% url 'user:setting_page' %}">设置</a></dd>
                    <dd><a href="{% url 'user:sign_out' %}">退出登录</a></dd>
                </dl>
                {% endif %}
            </li>
        </ul>
    </div>
{% endblock %}

{% block main %}
{% endblock %}

{% block footer %}
{% endblock %}
<script>
    layui.use(['layer', 'element'], function () {
        var element = layui.element;
        //…
    });
</script>
{% block script %}
{% endblock %}
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}
    <title>主页</title>
{% endblock %}

{% block main %}
    <h1 class="common-margin" style="alignment: center">Blog for YK</h1>
{% endblock %}

{% block script %}
    <script>
        $(function () {
            $('#nav_home').addClass('layui-this')
        });
    </script>
{% endblock %}



{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>Blog</title>#}
{#</head>#}
{#<body>#}
{#<h1>Blog for YK</h1>#}
{#<div>#}
{#    <a href="{% url 'authenticator:captcha' %}">获取图片验证码</a>#}
{#</div>#}
{#</body>#}
{#</html>#}